include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    directives_ordering: true
    unawaited_futures: true
